# pd.eval y pd.query in pandas

In [17]:
#pd.eval y pd.query es sólo para optimizar recursos. Es más rápido que otras funciones o métodos. 
##Eval genera datos calculados y query va a entregar dataframes


import pandas as pd
import numpy as np
nrows, ncols = 100000, 100
rng = np.random.RandomState(42)  #rng es range
df1, df2, df3, df4 = (pd.DataFrame(rng.rand(nrows, ncols)) for i in range(4))  #generar cuatro df

In [9]:
%timeit df1 + df2 + df3 + df4

116 ms ± 6.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [10]:
#pd.eval ejecuta la string que va como parámetro y permite ejecutar funciones aritméticas sobre mi df.
#Función de pandas y tiene un mejor rendimiento que apply o list comprenhension

%timeit pd.eval("df1 + df2 + df3 + df4")

61.4 ms ± 4.75 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [15]:
df1, df2, df3, df4, df5= (pd.DataFrame(rng.randint(0,1000, (100,3))) for i in range(5))

In [18]:
result1 = -df1 * df2 / (df3 + df4) - df5
result2 = pd.eval("df1 + df2 + df3 + df4 - df5")
np.allclose(result1, result2) #np.allclose es funcion que evalua byte by byte si una variable es igual a otra

C:\Users\Ramiro Antonio\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: PerformanceWarning: Alignment difference on axis 0 is larger than an order of magnitude on term 'df5', by more than 5; performance may suffer

False

In [21]:
df = pd.DataFrame(rng.rand(1000,3), columns= ["A", "B", "C"])
df.head()

          A         B         C
0  0.615875  0.525167  0.047354
1  0.330858  0.412879  0.441564
2  0.689047  0.559068  0.230350
3  0.290486  0.695479  0.852587
4  0.424280  0.534344  0.245216

In [22]:
result1 = (df["A"] + df["B"]) / (df["C"] - 1)
result2 = pd.eval("(df.A + df.B) / (df.C -1)")  #con eval no van corchetes, tiene que ir punto df.A, no df["A"]
np.allclose(result1, result2)

True

In [23]:
#Crear columna. Inplace lo guarda dentro del dataframe. De otra manera no lo agrega. 
df.eval("D = (A+B)/C", inplace = True)
df.head()

          A         B         C          D
0  0.615875  0.525167  0.047354  24.095868
1  0.330858  0.412879  0.441564   1.684325
2  0.689047  0.559068  0.230350   5.418335
3  0.290486  0.695479  0.852587   1.156439
4  0.424280  0.534344  0.245216   3.909296

In [24]:
#Cambiar valores
df.eval("D = (A-B)/C", inplace = True)
df.head()

          A         B         C         D
0  0.615875  0.525167  0.047354  1.915527
1  0.330858  0.412879  0.441564 -0.185752
2  0.689047  0.559068  0.230350  0.564268
3  0.290486  0.695479  0.852587 -0.475016
4  0.424280  0.534344  0.245216 -0.448844

In [27]:
#Para sumar variables
column_mean = df.mean(1)
print(column_mean)
result1 = df["A"] + column_mean
result2 = df.eval("A + @column_mean") #la arroba busca la variable o columna. Congela el resultado y facilita el análisis
np.allclose(result1, result2)

0      0.775981
1      0.249887
2      0.510683
3      0.340884
4      0.188749
5      0.040338
6      0.041682
7     -0.075885
8      0.353373
9      1.751152
10     0.290287
11     0.248720
12     0.522616
13     0.610032
14     0.274778
15     0.429958
16     0.202466
17     0.692229
18    -3.476720
19     0.071235
20     0.448523
21    -0.035753
22    -8.751397
23     0.146601
24     0.174587
25     1.076604
26     1.181968
27     0.061197
28     0.462930
29     9.284427
         ...
970    0.660545
971    0.687799
972    0.711724
973    0.371733
974    0.697471
975    0.119194
976    0.578747
977    0.593435
978   -1.498216
979    0.507564
980    0.020220
981    0.404264
982    0.247532
983    0.939454
984    1.587350
985    0.745707
986   -0.105253
987    0.050365
988    0.258291
989    0.464405
990    0.711346
991    0.254790
992    0.600418
993   -0.374712
994   -0.766538
995    0.558309
996    0.142245
997    0.026820
998    0.501173
999    0.240250
Length: 1000, dtype: float64

True

In [29]:
result1 = df[(df.A < 0.5) & (df.B < 0.5)]
result2 = pd.eval('df[(df.A < 0.5) & (df.B < 0.5)]')
np.allclose(result1, result2)

True

In [31]:
#The query function will perform comparison inside the dataframe itself. However, unlike eval, 
#it will return only the rows that meet the condition. 

#Eval genera datos calculados y query va a entregar dataframes
result2 = df.query("A < 0.5 and B < 0.5")
np.allclose(result1,result2)

True

In [32]:
Cmean = df["C"].mean()
result1 = df[(df.A < Cmean) & (df.B <Cmean)]
result2 = df.query("A < @Cmean and B < @Cmean")
np.allclose(result1, result2)

True

In [35]:
#LOOK-UP. Value-lookup en excel

df = pd.DataFrame([[1990, "a", 5,4,7,2], [1991, "c", 10, 1, 2, 0], [1992, "d",2,1,4,12], [1993, "a", 5,8,11,6]],
                 columns = ["Date", "best", "a", "b", "c", "d"])
df

   Date best   a  b   c   d
0  1990    a   5  4   7   2
1  1991    c  10  1   2   0
2  1992    d   2  1   4  12
3  1993    a   5  8  11   6

In [42]:
df["value"] = df.lookup(df.index, df["best"])

#si tienes dudas, fíjate en el dataframe en los valores
df

   Date best   a  b   c   d  value
0  1990    a   5  4   7   2      5
1  1991    c  10  1   2   0      2
2  1992    d   2  1   4  12     12
3  1993    a   5  8  11   6      5

In [40]:
#Booleanos de la columna 1
df1.get(df1[1] < 200)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.374540,0.950714,0.731994,0.598658,0.156019,0.155995,0.058084,0.866176,0.601115,0.708073,...,0.119594,0.713245,0.760785,0.561277,0.770967,0.493796,0.522733,0.427541,0.025419,0.107891
1,0.031429,0.636410,0.314356,0.508571,0.907566,0.249292,0.410383,0.755551,0.228798,0.076980,...,0.093103,0.897216,0.900418,0.633101,0.339030,0.349210,0.725956,0.897110,0.887086,0.779876
2,0.642032,0.084140,0.161629,0.898554,0.606429,0.009197,0.101472,0.663502,0.005062,0.160808,...,0.030500,0.037348,0.822601,0.360191,0.127061,0.522243,0.769994,0.215821,0.622890,0.085347
3,0.051682,0.531355,0.540635,0.637430,0.726091,0.975852,0.516300,0.322956,0.795186,0.270832,...,0.990505,0.412618,0.372018,0.776413,0.340804,0.930757,0.858413,0.428994,0.750871,0.754543
4,0.103124,0.902553,0.505252,0.826457,0.320050,0.895523,0.389202,0.010838,0.905382,0.091287,...,0.455657,0.620133,0.277381,0.188121,0.463698,0.353352,0.583656,0.077735,0.974395,0.986211
5,0.698162,0.536096,0.309528,0.813795,0.684731,0.162617,0.910927,0.822537,0.949800,0.725720,...,0.138827,0.640875,0.181880,0.345667,0.896788,0.473962,0.667558,0.172320,0.192289,0.040869
6,0.168935,0.278590,0.177010,0.088703,0.120636,0.460779,0.206334,0.364270,0.503417,0.690395,...,0.323679,0.425436,0.507610,0.242410,0.114837,0.610620,0.288631,0.581238,0.154363,0.481140
7,0.532589,0.051824,0.336604,0.134415,0.063375,0.989960,0.322354,0.809874,0.254641,0.681503,...,0.153351,0.586230,0.505889,0.611454,0.018110,0.872124,0.932118,0.565133,0.696651,0.922499
8,0.707239,0.152539,0.576288,0.606715,0.424131,0.736444,0.934367,0.925569,0.450839,0.113238,...,0.722267,0.855696,0.830220,0.397184,0.668085,0.204984,0.293148,0.896336,0.013002,0.085509
9,0.207886,0.026532,0.181435,0.583042,0.421425,0.892672,0.817444,0.341817,0.259423,0.379692,...,0.799416,0.694696,0.272145,0.590231,0.360974,0.091582,0.917314,0.136819,0.950237,0.446006
10,0.185133,0.541901,0.872946,0.732225,0.806561,0.658783,0.692277,0.849196,0.249668,0.489425,...,0.942732,0.649647,0.607737,0.512689,0.230670,0.176528,0.220486,0.186438,0.779584,0.350125
11,0.057843,0.969103,0.883786,0.927752,0.994908,0.173895,0.396242,0.758238,0.696021,0.153896,...,0.067351,0.582170,0.345883,0.620916,0.045742,0.871537,0.973489,0.968878,0.749652,0.130086
12,0.758263,0.024587,0.022124,0.323610,0.488643,0.770407,0.683295,0.445903,0.273627,0.997125,...,0.396923,0.132716,0.567541,0.689465,0.800587,0.200150,0.167483,0.104568,0.636430,0.706476
13,0.031586,0.936212,0.051971,0.541296,0.709061,0.870969,0.714087,0.801728,0.339450,0.814825,...,0.236050,0.073497,0.169758,0.519774,0.337003,0.828883,0.430888,0.248714,0.617145,0.706777
14,0.167042,0.167619,0.036671,0.736402,0.663805,0.474631,0.844170,0.805670,0.585354,0.868271,...,0.237544,0.373252,0.227270,0.073196,0.603449,0.668213,0.619490,0.463494,0.379786,0.863334
15,0.519082,0.479182,0.025642,0.341248,0.380196,0.398823,0.580172,0.533603,0.607905,0.764883,...,0.692436,0.991256,0.128394,0.104110,0.724339,0.578387,0.274161,0.079419,0.085658,0.894191
16,0.191867,0.323372,0.226656,0.354996,0.069424,0.519060,0.067613,0.800357,0.233712,0.540012,...,0.174839,0.502566,0.398663,0.146374,0.367534,0.068172,0.025812,0.135166,0.963115,0.549530
17,0.965822,0.432498,0.311816,0.506142,0.439512,0.105665,0.640826,0.216038,0.619588,0.650201,...,0.150169,0.737434,0.512222,0.680228,0.041673,0.084792,0.716323,0.072084,0.071257,0.012108
18,0.956501,0.737508,0.353251,0.296536,0.349703,0.774654,0.661371,0.185196,0.174109,0.098396,...,0.099178,0.401494,0.800071,0.204036,0.555085,0.733071,0.615985,0.188025,0.355385,0.783792
19,0.554227,0.005230,0.760991,0.035311,0.745734,0.202481,0.958073,0.367941,0.326932,0.148888,...,0.765513,0.158908,0.610225,0.135354,0.751375,0.656955,0.956615,0.068958,0.057055,0.282187
20,0.261706,0.246979,0.906255,0.249546,0.271950,0.759398,0.449740,0.776711,0.065366,0.487571,...,0.775612,0.964477,0.203766,0.523330,0.287138,0.792854,0.577593,0.634582,0.797914,0.395970
21,0.915090,0.533029,0.157955,0.695899,0.793261,0.316762,0.857179,0.906143,0.276904,0.983521,...,0.260287,0.907195,0.670732,0.560441,0.110989,0.447056,0.460358,0.864564,0.546648,0.380401
22,0.976800,0.110721,0.422548,0.042025,0.739904,0.918077,0.280037,0.858342,0.292218,0.910770,...,0.610780,0.280683,0.206993,0.516573,0.005506,0.007664,0.219069,0.036721,0.108026,0.338861
23,0.802586,0.572049,0.512668,0.293489,0.931754,0.397015,0.087093,0.617067,0.113838,0.345223,...,0.374553,0.166860,0.430529,0.142594,0.890097,0.345877,0.154460,0.025448,0.645822,0.636902
24,0.340604,0.071712,0.409629,0.311217,0.677121,0.605779,0.364594,0.217893,0.988036,0.454002,...,0.285784,0.203223,0.761798,0.386541,0.511275,0.492325,0.577279,0.865577,0.980739,0.407584
25,0.827519,0.764528,0.573529,0.956047,0.200475,0.109264,0.853962,0.439150,0.846969,0.893090,...,0.822535,0.803959,0.552501,0.520170,0.142876,0.775346,0.271409,0.496695,0.284274,0.133828
26,0.629558,0.054332,0.748645,0.317587,0.000135,0.511129,0.046852,0.276170,0.706976,0.062690,...,0.530938,0.595132,0.009924,0.464095,0.963499,0.519032,0.677542,0.311864,0.773991,0.772921
27,0.521296,0.976014,0.125550,0.016948,0.770158,0.807156,0.120207,0.265583,0.017552,0.293309,...,0.711723,0.981144,0.569540,0.259542,0.436996,0.593561,0.073082,0.622343,0.981178,0.190108
28,0.792595,0.907899,0.943702,0.960136,0.521460,0.977308,0.757310,0.161671,0.476900,0.718331,...,0.332191,0.693618,0.771123,0.654651,0.151595,0.875883,0.539095,0.282472,0.425228,0.037571
29,0.127867,0.765547,0.000012,0.416566,0.522510,0.054634,0.973078,0.226125,0.304199,0.303943,...,0.179256,0.800003,0.552707,0.396554,0.131715,0.865296,0.157273,0.309788,0.290046,0.871414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,0.235068,0.164406,0.204480,0.695623,0.620907,0.382475,0.405872,0.457494,0.045196,0.255887,...,0.451413,0.575522,0.211959,0.449871,0.856108,0.957182,0.425956,0.862490,0.109002,0.640205
99971,0.086616,0.958037,0.394750,0.960303,0.067067,0.032186,0.654181,0.703395,0.338712,0.013371,...,0.551509,0.598471,0.354176,0.887739,0.812608,0.579638,0.612157,0.237888,0.877288,0.421026
99972,0.379233,0.098840,0.248029,0.898884,0.891866,0.481938,0.921651,0.738893,0.596650,0.952869,...,0.898590,0.596512,0.390711,0.408632,0.328114,0.310661,0.028734,0.169148,0.927362,0.942131
99973,0.955915,0.137703,0.309331,0.165853,0.816364,0.265619,0.966744,0.550885,0.859650,0.690606,...,0.361937,0.956475,0.647543,0.270071,0.609093,0.094974,0.579509,0.009592,0.456242,0.225408
99974,0.131291,0.296078,0.572275,0.778057,0.817213,0.472782,0.082893,0.711263,0.038564,0.894496,...,0.722973,0.550548,0.939560,0.399065,0.641603,0.838948,0.896748,0.018142,0.894369,0.402269
99975,0.624783,0.727909,0.242309,0.722513,0.200420,0.020648,0.137692,0.240654,0.301705,0.339952,...,0.872916,0.121189,0.956220,0.112393,0.878292,0.534969,0.064356,0.588253,0.437656,0.056119
99976,0.360348,0.489840,0.157838,0.460680,0.760497,0.748482,0.999405,0.453320,0.623236,0.477265,...,0.211778,0.637911,0.514737,0.466302,0.704304,0.621937,0.692636,0.913747,0.061114,0.379862
99977,0.135283,0.630029,0.297396,0.163971,0.326433,0.705754,0.670912,0.257294,0.824275,0.614181,...,0.028971,0.029875,0.695664,0.898406,0.155490,0.953044,0.168571,0.031259,0.408373,0.350051
99978,0.140605,0.741371,0.767181,0.825379,0.920643,0.946323,0.441651,0.150067,0.013397,0.098166,...,0.580735,0.622445,0.255824,0.859527,0.627415,0.863540,0.879460,0.699038,0.587971,0.281232
99979,0.863263,0.335676,0.274821,0.617637,0.497933,0.695371,0.662931,0.790257,0.877444,0.291327,...,0.950058,0.846885,0.912907,0.095023,0.868228,0.613783,0.968045,0.159985,0.169796,0.436445
99980,0.552460,0.204735,0.047733,0.870659,0.889835,0.738405,0.047427,0.969874,0.207423,0.063859,...,0.965015,0.483943,0.246622,0.910535,0.380975,0.720555,0.958322,0.362283,0.973920,0.121145
99981,0.643029,0.379354,0.046678,0.604171,0.444815,0.357861,0.123796,0.693185,0.486504,0.245919,...,0.755066,0.799375,0.980545,0.072966,0.842906,0.587632,0.567313,0.676947,0.903825,0.028305
99982,0.301865,0.090758,0.915868,0.654676,0.087175,0.184472,0.351889,0.395700,0.740636,0.489956,...,0.365312,0.178367,0.236884,0.575780,0.270362,0.489001,0.216059,0.661324,0.503509,0.265636
99983,0.097869,0.478870,0.989644,0.356564,0.671516,0.173360,0.737817,0.545002,0.297150,0.268483,...,0.839236,0.706875,0.494209,0.063632,0.497177,0.726481,0.833540,0.010382,0.089958,0.950409
99984,0.922311,0.294625,0.973756,0.705608,0.800295,0.898579,0.202989,0.580991,0.064214,0.200963,...,0.844979,0.616330,0.456148,0.155657,0.175591,0.005538,0.714529,0.715092,0.119119,0.903085
99985,0.155191,0.286228,0.147640,0.595086,0.574276,0.484575,0.257927,0.582043,0.616274,0.667861,...,0.288585,0.445969,0.526146,0.615828,0.592677,0.005026,0.176165,0.796707,0.366958,0.636098
99986,0.633946,0.704074,0.722275,0.081072,0.569328,0.429807,0.503325,0.124079,0.907871,0.862132,...,0.704263,0.434238,0.015545,0.789037,0.815795,0.102522,0.474656,0.810993,0.912267,0.721398
99987,0.181690,0.016564,0.638306,0.756501,0.791164,0.014827,0.580145,0.193434,0.026889,0.812171,...,0.395551,0.344729,0.303583,0.124131,0.214831,0.870567,0.961686,0.897293,0.662502,0.374643
99988,0.639394,0.038863,0.508547,0.430462,0.057445,0.931414,0.934094,0.354220,0.323971,0.400175,...,0.185113,0.907019,0.214367,0.330600,0.156625,0.614805,0.412807,0.416301,0.222316,0.678655
99989,0.430002,0.993991,0.861573,0.872902,0.622845,0.414641,0.771986,0.141741,0.305980,0.445624,...,0.747635,0.488745,0.543308,0.422419,0.905223,0.629400,0.505090,0.735041,0.120995,0.179475
99990,0.347023,0.455422,0.580355,0.651958,0.605102,0.890908,0.790991,0.820513,0.548596,0.211588,...,0.626052,0.685421,0.216209,0.740264,0.712796,0.242585,0.326913,0.793120,0.565565,0.312076
99991,0.698221,0.295168,0.769935,0.270100,0.258748,0.576954,0.608767,0.176622,0.587120,0.834721,...,0.039653,0.404618,0.432767,0.185978,0.085630,0.801492,0.144680,0.291086,0.235920,0.951461
99992,0.345131,0.239160,0.165095,0.910056,0.367533,0.686016,0.323124,0.680629,0.529727,0.893343,...,0.276529,0.942943,0.825374,0.882899,0.728829,0.829473,0.211852,0.554510,0.429568,0.073304
99993,0.514883,0.454818,0.096102,0.188268,0.345554,0.375190,0.426944,0.284893,0.973188,0.316560,...,0.000172,0.533081,0.359184,0.140308,0.712595,0.016308,0.413832,0.205651,0.794271,0.750565
99994,0.273208,0.369597,0.495740,0.492283,0.525639,0.187136,0.322609,0.901747,0.882896,0.467634,...,0.837200,0.969355,0.574925,0.643373,0.439800,0.411788,0.840367,0.485335,0.828684,0.721273
99995,0.071979,0.439323,0.188588,0.586705,0.640611,0.662409,0.318503,0.600419,0.609742,0.390592,...,0.122887,0.491140,0.032855,0.567250,0.428673,0.421092,0.021024,0.398596,0.405897,0.869783
99996,0.313411,0.010490,0.469216,0.600825,0.451085,0.496918,0.983128,0.422056,0.719077,0.045588,...,0.072444,0.715574,0.300257,0.087290,0.130703,0.549202,0.287877,0.589258,0.516884,0.254370
99997,0.560873,0.647396,0.043068,0.282439,0.042950,0.346690,0.954034,0.603182,0.447768,0.888498,...,0.880079,0.508377,0.442052,0.621332,0.314942,0.131085,0.697310,0.111705,0.397560,0.988347
99998,0.710115,0.067999,0.611329,0.136199,0.054724,0.018160,0.911428,0.762005,0.245312,0.891027,...,0.249632,0.894231,0.342761,0.844330,0.659797,0.835561,0.117920,0.211202,0.931760,0.296913
99999,0.116834,0.461155,0.754556,0.250272,0.864631,0.588966,0.358260,0.655541,0.946702,0.145819,...,0.298095,0.496018,0.990856,0.368719,0.837910,0.244971,0.061637,0.933295,0.245149,0.388890

# Indexing

In [44]:
nba = pd.read_csv("nba-2.csv")

In [46]:
nba.describe()
print(len(nba))

458

In [47]:
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [48]:
nba.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [55]:
#Modificamos la variable
pd.crosstab(index=nba.Team, columns="count").sort_values(by=["count"], ascending=False)

col_0                   count
Team
New Orleans Pelicans       19
Memphis Grizzlies          18
New York Knicks            16
Milwaukee Bucks            16
Atlanta Hawks              15
Utah Jazz                  15
Toronto Raptors            15
San Antonio Spurs          15
Sacramento Kings           15
Portland Trail Blazers     15
Phoenix Suns               15
Philadelphia 76ers         15
Oklahoma City Thunder      15
Boston Celtics             15
Miami Heat                 15
Los Angeles Lakers         15
Los Angeles Clippers       15
Indiana Pacers             15
Houston Rockets            15
Golden State Warriors      15
Detroit Pistons            15
Denver Nuggets             15
Dallas Mavericks           15
Cleveland Cavaliers        15
Chicago Bulls              15
Charlotte Hornets          15
Brooklyn Nets              15
Washington Wizards         15
Minnesota Timberwolves     14
Orlando Magic              14

In [56]:
pd.crosstab(index=nba.Position, columns=nba.College)

College,Alabama,Arizona,Arizona State,Arkansas,Baylor,Belmont,Blinn College,Boston College,Boston University,Bowling Green,...,Washington State,Weber State,Westchester CC,Western Carolina,Western Kentucky,Western Michigan,Wichita State,Wisconsin,Wyoming,Xavier
Position,,,,,,,,,,,,,,,,,,,,,
C,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
PF,1,3,1,1,0,0,1,0,0,1,...,0,0,0,0,0,1,0,2,1,1
PG,1,2,0,1,0,0,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0
SF,1,5,0,1,1,0,0,1,0,0,...,0,0,0,0,1,0,1,1,0,0
SG,0,2,1,0,0,1,0,0,1,0,...,1,0,1,1,1,0,0,0,0,0

In [64]:
nba["sobrepeso"] = np.where(nba.Weight > 200, "Con Sobrepeso", "Sin sobrepeso")
nba.head(5)
pd.crosstab(index=nba.Position, columns=nba.sobrepeso)

sobrepeso  Con Sobrepeso  Sin sobrepeso
Position
C                     78              0
PF                    99              1
PG                    10             82
SF                    79              6
SG                    69             33

In [65]:
nba.index = RangeIndex(start=0, stop=50, step=2) #Range index empieza en el cero, va a tener 50 registros y va a ir de dos en dos

NameError: name 'RangeIndex' is not defined

In [70]:
#Cambiar el índice para que los puedas reacomodar

nba.index = nba.Team
nba.head(5)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,sobrepeso
Team,,,,,,,,,,
Boston Celtics,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Sin sobrepeso
Boston Celtics,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Con Sobrepeso
Boston Celtics,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Con Sobrepeso
Boston Celtics,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Sin sobrepeso
Boston Celtics,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Con Sobrepeso

In [71]:
nba.sort_index(axis=1).head(5) #ordena alfabeticamente las columnas

,Age,College,Height,Name,Number,Position,Salary,Team,Weight,sobrepeso
Team,,,,,,,,,,
Boston Celtics,25.0,Texas,6-2,Avery Bradley,0.0,PG,7730337.0,Boston Celtics,180.0,Sin sobrepeso
Boston Celtics,25.0,Marquette,6-6,Jae Crowder,99.0,SF,6796117.0,Boston Celtics,235.0,Con Sobrepeso
Boston Celtics,27.0,Boston University,6-5,John Holland,30.0,SG,NaN,Boston Celtics,205.0,Con Sobrepeso
Boston Celtics,22.0,Georgia State,6-5,R.J. Hunter,28.0,SG,1148640.0,Boston Celtics,185.0,Sin sobrepeso
Boston Celtics,29.0,NaN,6-10,Jonas Jerebko,8.0,PF,5000000.0,Boston Celtics,231.0,Con Sobrepeso

In [72]:
#Para seccionar el dataset
nba.set_index(["Team", "Position"])

                                                    Name  Number   Age Height  \
Team                   Position
Boston Celtics         PG                  Avery Bradley     0.0  25.0    6-2
                       SF                    Jae Crowder    99.0  25.0    6-6
                       SG                   John Holland    30.0  27.0    6-5
                       SG                    R.J. Hunter    28.0  22.0    6-5
                       PF                  Jonas Jerebko     8.0  29.0   6-10
                       PF                   Amir Johnson    90.0  29.0    6-9
                       PF                  Jordan Mickey    55.0  21.0    6-8
                       C                    Kelly Olynyk    41.0  25.0    7-0
                       PG                   Terry Rozier    12.0  22.0    6-2
                       PG                   Marcus Smart    36.0  22.0    6-4
                       C                 Jared Sullinger     7.0  24.0    6-9
                       PG                  Isaiah Thomas     4.0  27.0    5-9
                       SG                    Evan Turner    11.0  27.0    6-7
                       SG                    James Young    13.0  20.0    6-6
                       C                    Tyler Zeller    44.0  26.0    7-0
Brooklyn Nets          SG               Bojan Bogdanovic    44.0  27.0    6-8
                       SG                   Markel Brown    22.0  24.0    6-3
                       SG                Wayne Ellington    21.0  28.0    6-4
                       SG        Rondae Hollis-Jefferson    24.0  21.0    6-7
                       PG                   Jarrett Jack     2.0  32.0    6-3
                       SG                 Sergey Karasev    10.0  22.0    6-7
                       SG                Sean Kilpatrick     6.0  26.0    6-4
                       PG                   Shane Larkin     0.0  23.0   5-11
                       C                     Brook Lopez    11.0  28.0    7-0
                       PF               Chris McCullough     1.0  21.0   6-11
                       PF                    Willie Reed    33.0  26.0   6-10
                       PF                Thomas Robinson    41.0  25.0   6-10
                       C                      Henry Sims    14.0  26.0   6-10
                       PG                   Donald Sloan    15.0  28.0    6-3
                       PF                 Thaddeus Young    30.0  27.0    6-8
...                                                  ...     ...   ...    ...
Portland Trail Blazers SF                Al-Farouq Aminu     8.0  25.0    6-9
                       SG                Pat Connaughton     5.0  23.0    6-5
                       SG                   Allen Crabbe    23.0  24.0    6-6
                       C                        Ed Davis    17.0  27.0   6-10
                       SF               Maurice Harkless     4.0  23.0    6-9
                       SG               Gerald Henderson     9.0  28.0    6-5
                       C                     Chris Kaman    35.0  34.0    7-0
                       PF                 Meyers Leonard    11.0  24.0    7-1
                       PG                 Damian Lillard     0.0  25.0    6-3
                       SG                  C.J. McCollum     3.0  24.0    6-4
                       SG                   Luis Montero    44.0  23.0    6-7
                       C                   Mason Plumlee    24.0  26.0   6-11
                       PG                  Brian Roberts     2.0  30.0    6-1
                       PF                    Noah Vonleh    21.0  20.0    6-9
Utah Jazz              PF                  Trevor Booker    33.0  28.0    6-8
                       PG                     Trey Burke     3.0  23.0    6-1
                       SG                     Alec Burks    10.0  24.0    6-6
                       PG                     Dante Exum    11.0  20.0    6-6
                       PF                 Derrick Favors    15.0  24.0   6-10
                       C                     Rudy Gobert    27.0  23.0    7-1
                       SF                 Gordon Hayward    20.0  26.0    6-8
                       SG                    Rodney Hood     5.0  23.0    6-8
                       SF                     Joe Ingles     2.0  28.0    6-8
                       SF                  Chris Johnson    23.0  26.0    6-6
                       PF                     Trey Lyles    41.0  20.0   6-10
                       PG                   Shelvin Mack     8.0  26.0    6-3
                       PG                      Raul Neto    25.0  24.0    6-1
                       C                    Tibor Pleiss    21.0  26.0    7-3
                       C                     Jeff Withey    24.0  26.0    7-0
NaN                    NaN                           NaN     NaN   NaN    NaN

                                 Weight            College      Salary  \
Team                   Position
Boston Celtics         PG         180.0              Texas   7730337.0
                       SF         235.0          Marquette   6796117.0
                       SG         205.0  Boston University         NaN
                       SG         185.0      Georgia State   1148640.0
                       PF         231.0                NaN   5000000.0
                       PF         240.0                NaN  12000000.0
                       PF         235.0                LSU   1170960.0
                       C          238.0            Gonzaga   2165160.0
                       PG         190.0         Louisville   1824360.0
                       PG         220.0     Oklahoma State   3431040.0
                       C          260.0         Ohio State   2569260.0
                       PG         185.0         Washington   6912869.0
                       SG         220.0         Ohio State   3425510.0
                       SG         215.0           Kentucky   1749840.0
                       C          253.0     North Carolina   2616975.0
Brooklyn Nets          SG         216.0                NaN   3425510.0
                       SG         190.0     Oklahoma State    845059.0
                       SG         200.0     North Carolina   1500000.0
                       SG         220.0            Arizona   1335480.0
                       PG         200.0       Georgia Tech   6300000.0
                       SG         208.0                NaN   1599840.0
                       SG         219.0         Cincinnati    134215.0
                       PG         175.0         Miami (FL)   1500000.0
                       C          275.0           Stanford  19689000.0
                       PF         200.0           Syracuse   1140240.0
                       PF         220.0        Saint Louis    947276.0
                       PF         237.0             Kansas    981348.0
                       C          248.0         Georgetown    947276.0
                       PG         205.0          Texas A&M    947276.0
                       PF         221.0       Georgia Tech  11235955.0
...                                 ...                ...         ...
Portland Trail Blazers SF         215.0        Wake Forest   8042895.0
                       SG         206.0         Notre Dame    625093.0
                       SG         210.0         California    947276.0
                       C          240.0     North Carolina   6980802.0
                       SF         215.0         St. John's   2894059.0
                       SG         215.0               Duke   6000000.0
                       C          265.0   Central Michigan   5016000.0
                       PF         245.0           Illinois   3075880.0
                       PG         195.0        Weber State   4236287.0
                       SG         200.0             Lehigh   2525160.0
                       SG         185.0     Westchester CC    525093.0
                       C          235.0               Duke   1415520.0
                       PG         173.0             Dayton   2854940.0
                       PF         240.0            Indiana   2637720.0
Utah Jazz              PF         228.0            Clemson   4775000.0
                       PG         191.0           Michigan   2658240.0
                       SG         214.0           Colorado   9463484.0
                       PG         190.0                NaN   3777720.0
                       PF         265.0       Georgia Tech  12000000.0
                       C          245.0                NaN   1175880.0
                       SF         226.0             Butler  15409570.0
                       SG         206.0               Duke   1348440.0
                       SF         226.0                NaN   2050000.0
                       SF         206.0             Dayton    981348.0
                       PF         234.0           Kentucky   2239800.0
                       PG         203.0             Butler   2433333.0
                       PG         179.0                NaN    900000.0
                       C          256.0                NaN   2900000.0
                       C          231.0             Kansas    947276.0
NaN                    NaN          NaN                NaN         NaN

                                     sobrepeso
Team                   Position
Boston Celtics         PG        Sin sobrepeso
                       SF        Con Sobrepeso
                       SG        Con Sobrepeso
                       SG        Sin sobrepeso
                       PF        Con Sobrepeso
                       PF        Con Sobrepeso
                       PF        Con Sobrepeso
                       C         Con Sobrepeso
                       PG        Sin sobrepeso
                       PG        Con Sobrepeso
                       C         Con Sobrepeso
                       PG        Sin sobrepeso
                       SG        Con Sobrepeso
                       SG        Con Sobrepeso
                       C         Con Sobrepeso
Brooklyn Nets          SG        Con Sobrepeso
                       SG        Sin sobrepeso
                       SG        Sin sobrepeso
                       SG        Con Sobrepeso
                       PG        Sin sobrepeso
                       SG        Con Sobrepeso
                       SG        Con Sobrepeso
                       PG        Sin sobrepeso
                       C         Con Sobrepeso
                       PF        Sin sobrepeso
                       PF        Con Sobrepeso
                       PF        Con Sobrepeso
                       C         Con Sobrepeso
                       PG        Con Sobrepeso
                       PF        Con Sobrepeso
...                                        ...
Portland Trail Blazers SF        Con Sobrepeso
                       SG        Con Sobrepeso
                       SG        Con Sobrepeso
                       C         Con Sobrepeso
                       SF        Con Sobrepeso
                       SG        Con Sobrepeso
                       C         Con Sobrepeso
                       PF        Con Sobrepeso
                       PG        Sin sobrepeso
                       SG        Sin sobrepeso
                       SG        Sin sobrepeso
                       C         Con Sobrepeso
                       PG        Sin sobrepeso
                       PF        Con Sobrepeso
Utah Jazz              PF        Con Sobrepeso
                       PG        Sin sobrepeso
                       SG        Con Sobrepeso
                       PG        Sin sobrepeso
                       PF        Con Sobrepeso
                       C         Con Sobrepeso
                       SF        Con Sobrepeso
                       SG        Con Sobrepeso
                       SF        Con Sobrepeso
                       SF        Con Sobrepeso
                       PF        Con Sobrepeso
                       PG        Con Sobrepeso
                       PG        Sin sobrepeso
                       C         Con Sobrepeso
                       C         Con Sobrepeso
NaN                    NaN       Sin sobrepeso

[458 rows x 8 columns]